### ISSUE TITLE
not working on ios production

### ISSUE THREAD

**Issue by nitishk72** [builttoroam/device_calendar#272]
I have a flutter app which uses this plugin everything works fine on the local machine. 

- Working fine on Emulator
- Working fine on the Real device when running using XCode.

❌ Issue
- Not working when running using test flight

I don't know if my app is going to be accepted.  

```yaml
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  device_calendar: ^3.1.0
```

Using Swift for iOS `SWIFT_VERSION = 5.0;`
