### ISSUE TITLE
Calendar attributes from retrieveCalendars() only present in debug mode

### ISSUE THREAD

**Issue by steffomix** [builttoroam/device_calendar#484]
In production mode with sound null savety enabled the method 
DeviceCalendarPlugin().retrieveCalendars()
returns a correct amount of Calendars but without attributes like name or accountName. 

In debug mode or by running a debug version everything works as expected.

### pubspec:

```
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  background_location_tracker: # https://github.com/icapps/flutter-background-location-tracker
    path: ../git-packages/flutter-background-location-tracker
  
  flutter_osm_plugin: # https://github.com/liodali/osm_flutter
    path: ../git-packages/osm_flutter

  flutter_local_notifications: 13.0.0
  permission_handler: 10.2.0
  shared_preferences: 2.0.15
  path: 1.8.2
  http: 0.13.5
  sprintf: 7.0.0
  vector_math: 2.1.4
  path_provider: 2.0.13
  external_path: 1.0.3
  android_intent_plus: 3.1.6
  loading_animation_widget: 1.2.0
  device_calendar: 4.3.1 
  geolocator: 9.0.2
  file_manager: ^1.0.2
  fluttertoast: ^8.2.1
  cupertino_icons: 1.0.5

dependency_overrides:
  geolocator_android: 4.1.4
```

### permissions:
```

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_CALENDAR"/>
    <uses-permission android:name="android.permission.WRITE_CALENDAR"/>
    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
```
