### ISSUE TITLE
Does not build in release mode

### ISSUE THREAD

**Issue by andreystavitsky** [builttoroam/device_calendar#553]
device_calendar: ^4.3.2

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.3880])
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.9.6)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.92.0)
[√] Connected device (3 available)
[√] Network resources
```

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':device_calendar:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:\build\device_calendar\intermediates\merged_res\release\values\values.xml:2541: AAPT: error: resource android:attr/lStar not found.
```

**Comment by thomassth** [comment]
Try the 4.3.3 prerelease?

**Comment by andreystavitsky** [comment]
> Try the 4.3.3 prerelease?

same

**Comment by FlagElitov** [comment]
I also had a problem with running on the last Flutter version. And I've found the solution.
 
  Add this code to your pubspec.yaml, and it starts work.
  
```
  device_calendar:
    git:
      url: https://github.com/builttoroam/device_calendar
      ref: develop
```
or you can check prerelease
device_calendar: ^4.3.3-20240801

**Comment by andreystavitsky** [comment]
> Try the 4.3.3 prerelease?

I was wrong, it works with 4.3.3 prerelease

**Comment by gnunicorn** [comment]
Trying to build an `apk`, I still get this error on the prelease.

```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':package_info:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/DEV/acter/a3/app/build/package_info/intermediates/merged_res/release/values/values.xml:194: AAPT: error: resource android:attr/lStar not found.
```

My flutter
```
 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on Manjaro Linux 6.6.46-1-MANJARO, locale de_DE.utf8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

The part of pubspec:
```
[ben@slimbook app]$ grep device_calendar pubspec.lock 
  device_calendar:
      name: device_calendar
[ben@slimbook app]$ grep device_calendar -C 5 pubspec.lock 
      name: dbus
      sha256: "365c771ac3b0e58845f39ec6deebc76e3276aa9922b0cc60840712094d9047ac"
      url: "https://pub.dev"
    source: hosted
    version: "0.7.10"
  device_calendar:
    dependency: "direct main"
    description:
      name: device_calendar
      sha256: "23e3746e7e99dcbf2695f21a7270e97c374e99dcc2ee909d061688b1df88854b"
      url: "https://pub.dev"
    source: hosted
    version: "4.3.3-20240801"
  device_info_plus:
```

Regular run and bundle build seem fine.
